WIP

diff --git a/.github/workflows/test-prod-env-2.yml b/.github/workflows/test-prod-env-2.yml
--- a/.github/workflows/test-prod-env-2.yml
+++ b/.github/workflows/test-prod-env-2.yml
@@ -25,23 +25,13 @@ jobs:
     - name: Build custom App Docker image
       working-directory: code
       run: |
-        docker buildx build --platform linux/amd64 -t mpi-employment-interest-tool:latest --load .
+        docker buildx build --platform linux/amd64 -t mpi-employment-interest-tool:latest --output type=tar,dest=mpi-employment-interest-tool.tar .
 
     # Build the custom Nginx Docker image
     - name: Build custom Nginx Docker image
       working-directory: code
       run: |
-        docker buildx build --platform linux/amd64 -f Dockerfile.nginx -t custom-nginx:latest --load .
-
-    - name: Save application Docker image to tar file
-      working-directory: code
-      run: |
-        docker save mpi-employment-interest-tool:latest -o mpi-employment-interest-tool.tar
-
-    - name: Save custom Nginx Docker image to tar file
-      working-directory: code
-      run: |
-        docker save custom-nginx:latest -o custom-nginx.tar
+        docker buildx build --platform linux/amd64 -f Dockerfile.nginx -t custom-nginx:latest --output type=tar,dest=custom-nginx.tar .
 
     - name: Save SSH private key
       run: |
@@ -64,7 +54,7 @@ jobs:
             mpi@mpissh2.stijnrombouts.be:~/
     
     # Copy the .env.test.prod file to the vm and copy it to .env and .env.test.prod
-    - name: Copy .env.test.prod to VM
+    - name: Copy .env.test.prod to VM and setup environment
       run: |
         scp -o StrictHostKeyChecking=no \
             -o ProxyCommand="cloudflared access ssh --hostname %h --service-token-id ${{ secrets.SERVICE_TOKEN_ID }} --service-token-secret ${{ secrets.SERVICE_TOKEN_SECRET }}" \
@@ -75,7 +65,7 @@ jobs:
             -o ProxyCommand="cloudflared access ssh --hostname %h --service-token-id ${{ secrets.SERVICE_TOKEN_ID }} --service-token-secret ${{ secrets.SERVICE_TOKEN_SECRET }}" \
             -i ${{ secrets.SSH_PRIVATE_KEY_FILENAME }} \
             mpi@mpissh2.stijnrombouts.be \
-            "cp .env.test.prod .env"
+            "if [ -f /etc/laravel/app_key ]; then cat /etc/laravel/app_key >> .env.test.prod; else echo 'ERROR: /etc/laravel/app_key not found on server' >&2; exit 2; fi && cp .env.test.prod .env"
 
     # Stop the compose on the vm
     - name: Stop Docker Compose on VM
